spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: career-service

server:
  port: 8081

springdoc:
  api-docs:
    path: /api/v1/career-service/v3/api-docs

logging:
  level:
    root: INFO
    com.example.careerservice: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
