openapi: 3.0.3
info:
  title: Career Service
  version: 1.0.0
  description: API for scraping job listings and generating PDFs.
servers:
  - url: http://localhost:8081
paths:
  /api/v1/scrapper:
    $ref: "paths/scrapper/scrape.yaml#/scrape"
  /api/v1/pdf/generate:
     $ref: "paths/pdf/generate.yaml#/generate"
