openapi: 3.0.3
info:
  title: My API
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /scrapper:
    $ref: "paths/scrapper/scrape.yaml#/scrape"
  /api/v1/pdf/generate:
     $ref: "paths/pdf/generate.yaml#/generate"
